database_url: postgres://postgres:InvidiousPass123@postgres-invidious:5432/invidious
hmac_key: "SomethingSecureAndLong12345!"
external_port: 8080
https_only: false
registration_enabled: true
check_tables: true
use_innertube_for_captions: true
channel_threads: 1
full_refresh: false
player_storyboards: false
output_video_storyboards: false
feed_threads: 1
force_refresh_visitor_data: true

invidious_companion:
  - private_url: "http://invidious-companion:8282/companion"

invidious_companion_key: "1234567890abcdef"

jobs:
  clear_expired_items:
    enable: true
  refresh_channels:
    enable: true
  refresh_feeds:
    enable: true

default_user_preferences:
  quality: dash
  local: false
